name: Deploy CustomGPT

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Install Backend Dependencies
      run: |
        cd backend
        yarn install

    - name: Build Backend
      run: |
        cd backend
        yarn build

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        yarn install

    - name: Build Frontend
      run: |
        cd frontend
        yarn build

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: "custom-gpt-thirdweb"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
